all:
	g++ -O3 -std=c++11 -pthread MadN.cpp Calculator.cpp IOResults.cpp Player.cpp Position.cpp RatioAnalyser.cpp GamePlayer.cpp Game.cpp Tournament.cpp RandomPlayer.cpp SimplePlayer.cpp ImprovedSimplePlayer.cpp OptimalPlayer.cpp OptimalPlayerBM.cpp FastOptimalPlayerBMS.cpp Compressor.cpp CompressorR6.cpp Analyser.cpp Main.cpp -o madn.out
	mkdir -p log
	mkdir -p results
	mkdir -p backup